# Generated by Django 3.2.9 on 2023-10-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='', max_length=30)),
                ('Email', models.CharField(default='', max_length=30)),
                ('Number', models.IntegerField(default='')),
                ('Password', models.CharField(default='', max_length=30)),
                ('PAN', models.CharField(default='', max_length=30)),
                ('Balance', models.IntegerField(default='0')),
                ('Username', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
