# Generated by Django 3.2.9 on 2023-10-11 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Borrower', models.CharField(default='', max_length=30)),
                ('BorrowerMail', models.CharField(default='', max_length=30)),
                ('ApplicationDate', models.DateField(default=datetime.datetime.now)),
                ('ApplicationTime', models.TimeField(default=datetime.datetime.now)),
                ('LoanAmount', models.IntegerField(default='')),
                ('InterestPercentage', models.IntegerField(default='')),
                ('TermMonths', models.IntegerField(default='')),
                ('Monthly', models.IntegerField(default='')),
                ('NetEarnings', models.IntegerField(default='')),
                ('NextRepayment', models.DateField(default=datetime.datetime.now)),
                ('Status', models.IntegerField(default='')),
                ('Lender', models.CharField(default='', max_length=30)),
                ('LenderMail', models.CharField(default='', max_length=30)),
                ('SanctionDate', models.DateField(default=datetime.datetime.now)),
                ('SanctionTime', models.TimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='Username',
        ),
    ]
