# Generated by Django 3.2.9 on 2023-10-11 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20231011_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LenderMail', models.CharField(default='', max_length=100)),
                ('BorrowerMail', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=100)),
                ('Time', models.TimeField(default=datetime.datetime.now)),
                ('Date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
