# Generated by Django 3.2.9 on 2023-10-13 06:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_notificationdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionID', models.CharField(default='', max_length=30)),
                ('Purpose', models.CharField(default='', max_length=30)),
                ('TransactionDate', models.DateField(default=datetime.datetime.now)),
                ('TransactionTime', models.TimeField(default=datetime.datetime.now)),
                ('BorrowerUsername', models.CharField(default='', max_length=30)),
                ('LenderUsername', models.CharField(default='', max_length=30)),
                ('Amount', models.IntegerField(default='')),
                ('LenderMail', models.CharField(default='', max_length=30)),
                ('BorrowerMail', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
