# Generated by Django 3.2.9 on 2023-10-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_transactiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiondata',
            name='BorrowerBalance',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='transactiondata',
            name='LenderBalance',
            field=models.IntegerField(default='0'),
        ),
    ]
