# Generated by Django 3.2.9 on 2023-10-13 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20231013_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(default='', max_length=100)),
                ('SenderMail', models.CharField(default='', max_length=100)),
                ('ReceiverMail', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=100000)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 10, 13, 18, 16, 15, 874421))),
            ],
        ),
    ]
