# Generated by Django 3.2.9 on 2023-10-13 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_chatroom_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(default='', max_length=100)),
                ('SenderMail', models.CharField(default='', max_length=100)),
                ('ReceiverMail', models.CharField(default='', max_length=100)),
                ('Message', models.CharField(default='', max_length=100000)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 10, 13, 18, 17, 0, 870132))),
            ],
        ),
        migrations.RenameModel(
            old_name='ChatRoom',
            new_name='RoomData',
        ),
        migrations.DeleteModel(
            name='Messages',
        ),
    ]
