# Generated by Django 3.2.9 on 2023-10-13 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20231013_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedata',
            name='ReceiverName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='messagedata',
            name='SenderName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='messagedata',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 13, 21, 7, 38, 87344)),
        ),
    ]
